apiVersion: v1
kind: Service
metadata:
    name: "datlascluster-cf33"
    labels:
        app: "datlascluster-cf33"
spec:
    type: LoadBalancer
    ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
    selector:
        app: "datlascluster-cf33"