on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: datlascontainers.azurecr.io
        username: ${{ secrets.acr_datlascontainers_username }}
        password: ${{ secrets.acr_datlascontainers_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/14/buster" -f  "14/buster/Dockerfile" -t datlascontainers.azurecr.io/datlascluster:${{ github.sha }} --label dockerfile-path=14/buster/Dockerfile
        docker push datlascontainers.azurecr.io/datlascluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_datlascluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep postgres | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace postgres`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: postgres
        container-registry-url: datlascontainers.azurecr.io
        container-registry-username: ${{ secrets.acr_datlascontainers_username }}
        container-registry-password: ${{ secrets.acr_datlascontainers_password }}
        secret-name: datlasclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: postgres
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          datlascontainers.azurecr.io/datlascluster:${{ github.sha }}
        imagepullsecrets: |
          datlasclustedockerauth
